worker_processes auto;
events {
    worker_connections 1024;
}

rtmp {
    server {
        listen 1935;
        chunk_size 4096;
        allow publish all;

        application live {
            live on;
            record all;
            record_path /var/records;
            record_suffix -%Y-%m-%d-%H_%M_%S.flv;
            record_unique on;
            hls on;
            hls_path /var/www/html/hls;
            hls_fragment 3;
            hls_playlist_length 60;
        }
    }
}

http {
    include mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;

    server {
        listen 8080;
        server_name localhost;

        location / {
            root /var/www/html;
            index index.html;
            auth_basic "Area Restrita";
            auth_basic_user_file /etc/nginx/.htpasswd;
        }

        location /hls {
            types {
                application/vnd.apple.mpegurl m3u8;
                video/mp2t ts;
            }
            root /var/www/html;
            add_header Cache-Control no-cache;
            add_header Access-Control-Allow-Origin *;
            auth_basic "Area Restrita";
            auth_basic_user_file /etc/nginx/.htpasswd;
        }

        location /stat {
            rtmp_stat all;
            rtmp_stat_stylesheet stat.xsl;
        }

        location /stat.xsl {
            root /tmp/nginx-rtmp-module-master;
        }

        location /recordings {
            alias /var/records;
            autoindex on;
            auth_basic "Area Restrita";
            auth_basic_user_file /etc/nginx/.htpasswd;
        }
    }
}
