worker_processes auto;
events { worker_connections 1024; }

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    keepalive_timeout 65;

    server {
        listen 8888;
        server_name _;

        auth_basic           "Cameras - Area Restrita";
        auth_basic_user_file /etc/nginx/.htpasswd;

        # Painel + HLS
        location / {
            proxy_pass         http://srs:8080;
            proxy_http_version 1.1;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_buffering    off;
            add_header         Cache-Control no-cache;
            add_header         Access-Control-Allow-Origin *;
        }

        # API SRS (stats do painel)
        location /api/ {
            proxy_pass         http://srs:1985/api/;
            proxy_http_version 1.1;
            proxy_set_header   Host $host;
        }
    }
}
